### ISSUE TITLE
docker-compose  fail

### ISSUE THREAD

**Issue by myxss** [casibase/casibase#376]
![image](https://user-images.githubusercontent.com/33475775/138030236-df3757de-1a00-4ce5-87b3-7ca0279dde2a.png)

**Comment by ComradeProgrammer** [comment]
@myxss , after a brief investigation, I believe that:  
1. This output comes out from https://github.com/casbin/casnode/blob/b315f58566cfc9573410d95d13da027fc79314e6/go-dockerfile#L13
2. In spite of the message, **this docker image can still be built successfully** and docker-compose up can success too. Therefore, to some extent, this weird message is not a very big problem

Hope that these information can help

**Comment by hsluoyz** [comment]
@myxss any update?
